export const GET_RECOMMEND_TOP_BANNER_ACTION = "recommend/GET_RECOMMEND_TOP_BANNER_ACTION";
export const GET_RECOMMEND_TOP_BANNER = "recommend/GET_RECOMMEND_TOP_BANNER"

export const GET_RECOMMEND_HOT_RECOMMEND_ACTION = "recommend/GET_RECOMMEND_HOT_RECOMMEND_ACTION"
export const GET_RECOMMEND_HOT_RECOMMEND = "recommend/GET_RECOMMEND_HOT_RECOMMEND"

export const GET_RECOMMEND_NEW_ALBUM_ACTION = "recommend/GET_RECOMMEND_NEW_ALBUM_ACTION";
export const GET_RECOMMEND_NEW_ALBUM = "recommend/GET_RECOMMEND_NEW_ALBUM";

export const GET_RECOMMEND_RANKING_LIST_ACTION = "recommend/GET_RECOMMEND_RANKING_LIST_ACTION";
export const GET_CLOUD_SOARING_MUSIC_RANKING = "recommend/GET_CLOUD_SOARING_MUSIC_RANKING";
export const GET_CLOUD_NEW_MUSIC_RANKING = "recommend/GET_CLOUD_NEW_MUSIC_RANKING";
export const GET_ORIGINAL_MUSIC_RANKING = "recommend/GET_ORIGINAL_MUSIC_RANKING";




// 下面是toplist路由里用到的常量
export const GET_ALL_TOPLIST_ACTION = "toplist/GET_ALL_TOPLIST_ACTION";
export const GET_ALL_TOPLIST = "toplist/GET_ALL_TOPLIST";
export const GET_TOPLIST_DETAIL_BY_ID_ACTION = "toplist/GET_TOPLIST_DETAIL_BY_ID_ACTION";
export const GET_TOPLIST_DETAIL_BY_ID = "toplist/GET_TOPLIST_DETAIL_BY_ID";
export const GET_LATEST_COMMENT_BY_PAGE_ACTION = "toplist/GET_LATEST_COMMENT_BY_PAGE_ACTION";
export const GET_LATEST_COMMENT_BY_PAGE = "toplist/GET_LATEST_COMMENT_BY_PAGE";
export const GET_LATEST_COMMENT_BY_ID = "toplist/GET_LATEST_COMMENT_BY_ID";

// 下面是playlist路由里用到的常量
export const GET_ALL_CATEGORY_ACTION = "playlist/GET_ALL_CATEGORY_ACTION";
export const GET_ALL_CATEGORY = "playlist/GET_ALL_CATEGORY";

export const GET_CATEGORY_LIST_BY_CAT_ACTION = "playlist/GET_CATEGORY_LIST_BY_CAT_ACTION";
export const GET_CATEGORY_LIST_BY_CAT = "playlist/GET_CATEGORY_LIST_BY_CAT";
export const ADD_NEW_PAGE_LIST = "playlist/ADD_NEW_PAGE_LIST";

export const GET_ALBUM_BY_AREA_AND_PAGE_ACTION = "album/GET_ALBUM_BY_AREA_AND_PAGE_ACTION";
export const GET_ALBUM_BY_AREA_AND_PAGE = "album/GET_ALBUM_BY_AREA_AND_PAGE";
export const ADD_ALBUM_PAGE_LIST = "album/ADD_ALBUM_PAGE_LIST";


export const GET_TOP_ARTISTS_ACTION = "artists/GET_TOP_ARTISTS_ACTION";
export const GET_TOP_ARTISTS = "artists/GET_TOP_ARTISTS";

export const GET_ARTISTS_RANKING_BY_ID_AND_INITIAL_ACTION = "artists/GET_ARTISTS_RANKING_BY_ID_AND_INITIAL_ACTION";
export const GET_ARTISTS_RANKING_BY_ID_AND_INITIAL = "artists/GET_ARTISTS_RANKING_BY_ID_AND_INITIAL";
export const ADD_ARTISTS_INITIAL_LIST = "artists/ADD_ARTISTS_INITIAL_LIST";


export const GET_DJRADIO_CATELIST_ACTION = "djradio/GET_DJRADIO_CATELIST_ACTION";
export const GET_DJRADIO_CATELIST = "djradio/GET_DJRADIO_CATELIST";
export const GET_NEW_DJ_RADIO_ACTION = "djradio/GET_NEW_DJ_RADIO_ACTION";
export const GET_NEW_DJ_RADIO = "djradio/GET_NEW_DJ_RADIO";
export const GET_HOT_DJ_RADIO_ACTION = "djradio/GET_HOT_DJ_RADIO_ACTION";
export const GET_HOT_DJ_RADIO = "djradio/GET_HOT_DJ_RADIO";
export const ADD_DJ_RADIO_PAGE_LIST = "djradio/ADD_DJ_RADIO_PAGE_LIST";


export const GET_DISPLAY_MUSIC_ACTIONS = "song/GET_DISPLAY_MUSIC_ACTIONS";
export const GET_DISPLAY_MUSIC = "songs/GET_DISPLAY_MUSIC";
export const GET_NEW_COMMENT_BY_ID_AND_PAGE_ACTION = "songs/GET_NEW_COMMENT_BY_ID_AND_PAGE_ACTION";
export const GET_NEW_COMMENT_BY_ID_AND_PAGE = "songs/GET_NEW_COMMENT_BY_ID_AND_PAGE";


// 有关歌曲播放的常量
export const GET_PLAYLIST_MUSIC_LIST_BY_ID_ACTION = "audio-play-list/GET_PLAYLIST_MUSIC_LIST_BY_ID_ACTION";
export const GET_ALBUM_MUSIC_LIST_BY_ID_ACTION = "audio-play-list/GET_ALBUM_MUSIC_LIST_BY_ID_ACTION";
export const GET_SINGLE_MUSIC_BY_ID_ACTION = "audio-play-list/GET_SINGLE_MUSIC_BY_ID_ACTION";
export const GET_PLAYLIST_MUSIC_LIST_BY_ID = "audio-play-list/GET_PLAYLIST_MUSIC_LIST_BY_ID";
export const GET_ALBUM_MUSIC_LIST_BY_ID = "audio-play-list/GET_ALBUM_MUSIC_LIST_BY_ID";
export const GET_SINGLE_MUSIC_BY_ID = "audio-play-list/GET_SINGLE_MUSIC_BY_ID"; 

export const CHANGE_CURRENT_MUSIC_LIST = "audio-play-list/CHANGE_CURRENT_MUSIC_LIST";

export const CHANGE_CURRENT_MUSIC_BY_ID = "audio-play-list/CHANGE_CURRENT_MUSIC_BY_ID";
export const CHANGE_CURRENT_MUSIC_BY_MODE = "audio-play-list/CHANGE_CURRENT_MUSIC_BY_MODE";
export const DELETE_CURRENT_MUSIC = "audio-play-list/DELETE_CURRENT_MUSIC";
export const GET_LYRIC_ACTION = "audio-play-list/GET_LYRIC_ACTION";
export const GET_LYRIC = "audio-play-list/GET_LYRIC";
export const CLEAR_MUSIC_LIST = "audio-play-list/CLEAR_MUSIC_LIST";